# Generated by Django 3.2.5 on 2022-08-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texapp', '0003_auto_20220817_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=50)),
                ('street_address', models.CharField(max_length=50)),
                ('street_number', models.IntegerField()),
                ('zip_code', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
            ],
        ),
    ]
