# Generated by Django 3.2.5 on 2022-08-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texapp', '0004_addresse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='paragraph',
        ),
        migrations.AddField(
            model_name='letter',
            name='body',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
