# Generated by Django 3.2.5 on 2022-08-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texapp', '0008_alter_letter_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='salutation',
            field=models.CharField(blank=True, default='Dear', max_length=50),
        ),
        migrations.AlterField(
            model_name='letter',
            name='sign_off',
            field=models.CharField(blank=True, default='Best', max_length=50),
        ),
    ]
