# Generated by Django 3.2.5 on 2022-08-23 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texapp', '0009_auto_20220820_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='letter',
            name='enclosed',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='letter',
            name='ps',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
