# Generated by Django 3.2.5 on 2022-08-23 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texapp', '0011_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
