# Generated by Django 3.2.5 on 2022-08-23 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texapp', '0014_auto_20220823_1809'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Addresse',
        ),
    ]
