# Generated by Django 3.2.5 on 2022-08-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texapp', '0015_delete_addresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileaddressee',
            name='formal_relationship',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='letter',
            name='reference_bit',
            field=models.BooleanField(),
        ),
    ]
