# Generated by Django 3.2.5 on 2022-08-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texapp', '0016_auto_20220824_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileaddressee',
            name='salutation',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
