# Generated by Django 3.2.5 on 2022-08-25 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('texapp', '0017_profileaddressee_salutation'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='addressee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='texapp.profileaddressee'),
        ),
    ]
