# Generated by Django 3.2.5 on 2022-08-25 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('texapp', '0018_letter_addressee'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileaddressee',
            name='preferred_name',
            field=models.CharField(default='Mom', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='letter',
            name='addressee',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='texapp.profileaddressee'),
        ),
    ]
