# Generated by Django 3.2.5 on 2022-08-25 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texapp', '0019_auto_20220825_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='letter',
            old_name='salutation',
            new_name='greeting',
        ),
    ]
