# Generated by Django 3.2.5 on 2022-08-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texapp', '0020_rename_salutation_letter_greeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileaddressee',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
